[versions]
architectury-plugin = "3.4-SNAPSHOT"
architectury-loom = "1.7-SNAPSHOT"
shadow = "8.1.1"
[plugins]
architectury-plugin = { id = "architectury-plugin", version.ref = "architectury-plugin" }
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
[libraries]


